### Get All Categories
GET http://localhost:3000/api/categories
X-API-key: SECRET
Accept: application/json

### Create New Category
POST http://localhost:3000/api/categories
X-API-key: SECRET
Content-Type: application/json

{
  "name": "barang"
}

### Find Category By Id
GET http://localhost:3000/api/categories/100
X-API-key: SECRET
Accept: application/json

### Update Category By Id
PUT http://localhost:3000/api/categories/1
X-API-key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": "Update Gadget"
}

### Delete Category By Id
DELETE http://localhost:3000/api/categories/1
X-API-key: SECRET
Accept: application/json